FROM registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7
LABEL maintainer="Deven Phillips <deven.phillips@redhat.com>"

LABEL com.redhat.component="jenkins-slave-selenium-chrome-rhel7-docker" \
      name="openshift3/jenkins-slave-selenium-chrome-rhel7" \
      version="3.10" \
      architecture="x86_64" \
      release="1" \
      io.k8s.display-name="Jenkins Slave Selenium Chrome" \
      io.k8s.description="The jenkins agent to run Selenium with a headless Chrome browser." \
      io.openshift.tags="openshift,jenkins,slave,selenium,chrome"