apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jenkins.service_account_name | default "jenkins" | quote }}
  labels:
    app: jenkins
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins"}}